### ISSUE TITLE
Version 0.4 of scikit-optimize 

### ISSUE THREAD

**Issue by betatim** [conda-forge/scikit-optimize-feedstock#1]
A bit of a conda-forge newbie, is this the right place to discuss updating the recipe for a new release?

Maybe @pmlandwehr could help me modify the recipe for the new version we released today.

One complication (maybe?) is that we have a new dependency ([scikit-garden](https://github.com/scikit-garden/scikit-garden)) which needs cython to build. Would the first step be to add a conda-forge recipe for scikit-garden?

**Comment by pmlandwehr** [comment]
Hey sir - yep, adding scikit garden would be the first step for that. I actually [started working on a pull](https://github.com/conda-forge/staged-recipes/pull/3352) but ended up putting it on hold because it was complicated & my time has been short. If you're interested in picking it up...
