### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/scikit-optimize-feedstock#8]
Seems this repo was overlooked by the regrocf-autotickbot? At least, I don't see a PR for version 0.6, which was released about 9 months ago: https://github.com/scikit-optimize/scikit-optimize/releases

**Comment by h-vetinari** [comment]
Turns out the package was only posted to github, and not to PyPI; hence why the bot couldn't pick it up...

**Comment by holgern** [comment]
I updated scikit-optimize to 0.7, you can find the working PR here:
#11
